### ISSUE TITLE
Unknown command: scout/index/import

### ISSUE THREAD

**Issue by bphippen** [Rias500/craft3-scout#1]
Hi Rias, I'm getting "Unknown command: scout/index/import" when trying to run the import for the first time.

Edit** 
This wasn't working locally with MAMP but I did get it to work using a local virtual box container.

**Comment by Rias500** [comment]
Seems like it was more of a MAMP issue then, glad you got it to work!

**Comment by matevisky** [comment]
Is there any better workaround for this? The problem is many:

- It is not working at all if we have clouser of any entry
- I am not able to say explicitly what try to push to algolia, because the mapping logic is after the queue and not before

So maybe it would be better to put the mapping logic before the queue push, also it could avoid the clouser issue I guess and would give us the freedom to skip the not mapped Entries.

Please let me know if you do not have time to do it or to check it, I know it is a big change. Thank you for the great code anyway!!! Greatly appreciated!
